chore: update vercel

diff --git a/.github/workflows/refresh-data-pipeline.yml b/.github/workflows/refresh-data-pipeline.yml
--- a/.github/workflows/refresh-data-pipeline.yml
+++ b/.github/workflows/refresh-data-pipeline.yml
@@ -98,5 +98,23 @@ jobs:
         env:
           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
         run: |
-          curl -X POST "https://api.vercel.com/v13/deployments/{deployment_id}/retrigger" \
-            -H "Authorization: Bearer $VERCEL_TOKEN"
+          # Fetch the latest deployment
+          PROJECT_ID="energy-data-exploration"
+          DEPLOYMENTS=$(curl -X GET "https://api.vercel.com/v6/deployments?app=$PROJECT_ID" \
+            -H "Authorization: Bearer $VERCEL_TOKEN" \
+            -H "Content-Type: application/json")
+          
+          echo "Deployments: $DEPLOYMENTS"
+
+          DEPLOYMENT_ID=$(echo "$DEPLOYMENTS" | jq -r '.deployments[0].uid')
+          if [[ -z "$DEPLOYMENT_ID" ]]; then
+            echo "Failed to fetch the latest deployment ID."
+            exit 1
+          fi
+
+          echo "Latest Deployment ID: $DEPLOYMENT_ID"
+
+          # Trigger the redeploy
+          npm i -g vercel
+          vercel --token $VERCEL_TOKEN
+          vercel redeploy $DEPLOYMENT_ID
